[0m19:33:30.725643 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77d9f2b137d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77d9f517dac0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77d9f2f4d5e0>]}


============================== 19:33:30.729263 | 10e78e60-a689-40e6-9872-5a474c0d8fdb ==============================
[0m19:33:30.729263 [info ] [MainThread]: Running with dbt=1.10.9
[0m19:33:30.730325 [debug] [MainThread]: running dbt with arguments {'target_path': 'None', 'cache_selected_only': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'indirect_selection': 'eager', 'write_json': 'True', 'use_experimental_parser': 'False', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'log_path': 'logs', 'invocation_command': 'dbt init telegram_dbt', 'partial_parse': 'True', 'warn_error': 'None', 'log_format': 'default', 'introspect': 'True', 'no_print': 'None', 'fail_fast': 'False', 'log_cache_events': 'False', 'empty': 'None', 'static_parser': 'True', 'printer_width': '80', 'profiles_dir': '/home/chalasimon/.dbt', 'quiet': 'False'}
[0m19:33:30.741132 [info ] [MainThread]: Creating dbt configuration folder at /home/chalasimon/.dbt
[0m19:33:30.758720 [debug] [MainThread]: Starter project path: /home/chalasimon/Documents/10academy/week 7/challenge/Telegram-Medical-Insights/.venv/lib/python3.12/site-packages/dbt/include/starter_project
[0m19:33:30.766997 [info ] [MainThread]: 
Your new dbt project "telegram_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m19:33:30.767909 [info ] [MainThread]: Setting up your profile.
[0m19:37:34.655314 [info ] [MainThread]: Profile telegram_dbt written to /home/chalasimon/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m19:37:34.656655 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 244.00565, "process_in_blocks": "26640", "process_kernel_time": 0.20904, "process_mem_max_rss": "102412", "process_out_blocks": "80", "process_user_time": 1.906368}
[0m19:37:34.657321 [debug] [MainThread]: Command `dbt init` succeeded at 19:37:34.657182 after 244.01 seconds
[0m19:37:34.657850 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77d9f2bb1670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77d9f2b137d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77d9f3616f00>]}
[0m19:37:34.658520 [debug] [MainThread]: Flushing usage events
[0m19:37:36.324405 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:34:58.047387 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72a076d84fe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72a074e9b080>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72a074a7c8f0>]}


============================== 08:34:58.051080 | 801f3c4a-960e-4e91-b22c-7f7d1b7e3cd0 ==============================
[0m08:34:58.051080 [info ] [MainThread]: Running with dbt=1.10.9
[0m08:34:58.051912 [debug] [MainThread]: running dbt with arguments {'use_colors': 'True', 'printer_width': '80', 'target_path': 'None', 'empty': 'None', 'fail_fast': 'False', 'log_cache_events': 'False', 'log_path': 'logs', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'log_format': 'default', 'cache_selected_only': 'False', 'indirect_selection': 'eager', 'static_parser': 'True', 'debug': 'False', 'warn_error': 'None', 'version_check': 'True', 'partial_parse': 'True', 'introspect': 'True', 'send_anonymous_usage_stats': 'True', 'use_experimental_parser': 'False', 'profiles_dir': '/home/chalasimon/.dbt', 'quiet': 'False', 'no_print': 'None', 'invocation_command': 'dbt docs serve', 'write_json': 'True'}
[0m08:34:58.052675 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/chalasimon/Documents/10academy/week 7/challenge/Telegram-Medical-Insights/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:34:58.053846 [debug] [MainThread]: Resource report: {"command_name": "serve", "command_success": false, "command_wall_clock_time": 0.07324561, "process_in_blocks": "0", "process_kernel_time": 0.147889, "process_mem_max_rss": "98604", "process_out_blocks": "16", "process_user_time": 1.673754}
[0m08:34:58.054526 [debug] [MainThread]: Command `dbt docs serve` failed at 08:34:58.054402 after 0.07 seconds
[0m08:34:58.055047 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72a074df51f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72a074440140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72a076d84fe0>]}
[0m08:34:58.055591 [debug] [MainThread]: Flushing usage events
[0m08:34:59.057766 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:36:31.165782 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76838d242cf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76838f0e5ca0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76838d3fc860>]}


============================== 08:36:31.170756 | e592bb60-7f6b-4a55-9ee0-105331f1c155 ==============================
[0m08:36:31.170756 [info ] [MainThread]: Running with dbt=1.10.9
[0m08:36:31.171919 [debug] [MainThread]: running dbt with arguments {'static_parser': 'True', 'write_json': 'True', 'partial_parse': 'True', 'invocation_command': 'dbt run', 'profiles_dir': '/home/chalasimon/.dbt', 'debug': 'False', 'indirect_selection': 'eager', 'version_check': 'True', 'quiet': 'False', 'log_path': 'logs', 'empty': 'False', 'target_path': 'None', 'use_experimental_parser': 'False', 'warn_error': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'introspect': 'True', 'log_cache_events': 'False', 'fail_fast': 'False', 'no_print': 'None', 'cache_selected_only': 'False', 'log_format': 'default', 'printer_width': '80'}
[0m08:36:31.172662 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/chalasimon/Documents/10academy/week 7/challenge/Telegram-Medical-Insights/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:36:31.173852 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.09074684, "process_in_blocks": "0", "process_kernel_time": 0.162857, "process_mem_max_rss": "98604", "process_out_blocks": "8", "process_user_time": 1.673534}
[0m08:36:31.174503 [debug] [MainThread]: Command `dbt run` failed at 08:36:31.174371 after 0.09 seconds
[0m08:36:31.175030 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76838d45a4e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76838c6c7260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76838ce58560>]}
[0m08:36:31.175749 [debug] [MainThread]: Flushing usage events
[0m08:36:32.078587 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m01:37:39.063363 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78e83bacfbc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78e83baccbf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78e83bb5da00>]}


============================== 01:37:39.090715 | b5f8777d-00ba-48b3-b6d9-82d0d535f86e ==============================
[0m01:37:39.090715 [info ] [MainThread]: Running with dbt=1.10.9
[0m01:37:39.091751 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/chalasimon/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m01:37:39.092482 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/chalasimon/Documents/10academy/week 7/challenge/Telegram-Medical-Insights/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:37:39.106726 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.1459299, "process_in_blocks": "30544", "process_kernel_time": 0.296127, "process_mem_max_rss": "98720", "process_out_blocks": "8", "process_user_time": 2.080787}
[0m01:37:39.107596 [debug] [MainThread]: Command `dbt run` failed at 01:37:39.107422 after 0.15 seconds
[0m01:37:39.108381 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78e83b5b4ad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78e83bce9d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78e83baccbf0>]}
[0m01:37:39.109259 [debug] [MainThread]: Flushing usage events
[0m01:37:40.841049 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m01:38:27.243661 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x760abd117d70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x760abce99700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x760abce9a4b0>]}


============================== 01:38:27.247097 | 53ed4898-0832-4b4d-b970-acb3fa0d0b8c ==============================
[0m01:38:27.247097 [info ] [MainThread]: Running with dbt=1.10.9
[0m01:38:27.248123 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/chalasimon/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m01:38:27.249240 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/chalasimon/Documents/10academy/week 7/challenge/Telegram-Medical-Insights/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:38:27.250458 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.072918825, "process_in_blocks": "0", "process_kernel_time": 0.166662, "process_mem_max_rss": "98992", "process_out_blocks": "16", "process_user_time": 1.653654}
[0m01:38:27.251256 [debug] [MainThread]: Command `dbt run` failed at 01:38:27.251120 after 0.07 seconds
[0m01:38:27.251765 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x760abca72000>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x760abd6c8ec0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x760abd33ec60>]}
[0m01:38:27.252291 [debug] [MainThread]: Flushing usage events
[0m01:38:28.375052 [debug] [MainThread]: An error was encountered while trying to flush usage events
